In [1]:
from script.photostereo import photometry
import cv2 as cv
import time
import numpy as np

In [13]:
import requests
import json
import os

In [16]:
from datetime import datetime, timedelta

start_date = datetime(2023, 10, 17)
end_date = datetime(2023, 11, 9)

current_date = start_date
date_list = []

while current_date <= end_date:
    date_list.append(current_date.strftime("%Y-%m-%d") + "T22:55")
    current_date += timedelta(days=1)

date_list

['2023-10-17T22:55',
 '2023-10-18T22:55',
 '2023-10-19T22:55',
 '2023-10-20T22:55',
 '2023-10-21T22:55',
 '2023-10-22T22:55',
 '2023-10-23T22:55',
 '2023-10-24T22:55',
 '2023-10-25T22:55',
 '2023-10-26T22:55',
 '2023-10-27T22:55',
 '2023-10-28T22:55',
 '2023-10-29T22:55',
 '2023-10-30T22:55',
 '2023-10-31T22:55',
 '2023-11-01T22:55',
 '2023-11-02T22:55',
 '2023-11-03T22:55',
 '2023-11-04T22:55',
 '2023-11-05T22:55',
 '2023-11-06T22:55',
 '2023-11-07T22:55',
 '2023-11-08T22:55',
 '2023-11-09T22:55']

In [22]:
from urllib.request import urlretrieve

output_directory = "./test_data"

if not os.path.exists(output_directory):
    os.makedirs(output_directory)

i = 0
for date in date_list:
    api_url = f"https://svs.gsfc.nasa.gov/api/dialamoon/{date}"
    
    try:
        response = requests.get(api_url)
        response.raise_for_status()

        moon_data = response.json()
        image_url = moon_data["image"]["url"]

        print(f"Date: {date}, Image URL: {image_url}")

        # Extracting the filename from the URL
        filename = os.path.join(output_directory, f"moon.{i}.jpg")

        # Download the image
        urlretrieve(image_url, filename)
        print(f"Downloaded: {filename}")
        i += 1
    except requests.exceptions.RequestException as e:
        print(f"Error fetching data for {date}: {e}")

Date: 2023-10-17T22:55, Image URL: https://svs.gsfc.nasa.gov/vis/a000000/a005000/a005048/frames/730x730_1x1_30p/moon.6960.jpg
Downloaded: ./test_data/moon.0.jpg
Date: 2023-10-18T22:55, Image URL: https://svs.gsfc.nasa.gov/vis/a000000/a005000/a005048/frames/730x730_1x1_30p/moon.6984.jpg
Downloaded: ./test_data/moon.1.jpg
Date: 2023-10-19T22:55, Image URL: https://svs.gsfc.nasa.gov/vis/a000000/a005000/a005048/frames/730x730_1x1_30p/moon.7008.jpg
Downloaded: ./test_data/moon.2.jpg
Date: 2023-10-20T22:55, Image URL: https://svs.gsfc.nasa.gov/vis/a000000/a005000/a005048/frames/730x730_1x1_30p/moon.7032.jpg
Downloaded: ./test_data/moon.3.jpg
Date: 2023-10-21T22:55, Image URL: https://svs.gsfc.nasa.gov/vis/a000000/a005000/a005048/frames/730x730_1x1_30p/moon.7056.jpg
Downloaded: ./test_data/moon.4.jpg
Date: 2023-10-22T22:55, Image URL: https://svs.gsfc.nasa.gov/vis/a000000/a005000/a005048/frames/730x730_1x1_30p/moon.7080.jpg
Downloaded: ./test_data/moon.5.jpg
Date: 2023-10-23T22:55, Image URL:

In [23]:
from PIL import Image
import os

input_directory = "./test_data"
output_directory = "./bmp_data"

if not os.path.exists(output_directory):
    os.makedirs(output_directory)

for filename in os.listdir(input_directory):
    input_path = os.path.join(input_directory, filename)
    output_path = os.path.join(output_directory, os.path.splitext(filename)[0] + ".bmp")

    try:
        with Image.open(input_path) as img:
            # Convert the image to BMP format
            img.convert("RGB").save(output_path, "BMP")

        print(f"Converted: {output_path}")
    except Exception as e:
        print(f"Error processing {input_path}: {e}")

Error processing ./test_data/.DS_Store: cannot identify image file './test_data/.DS_Store'
Converted: ./bmp_data/moon.23.bmp
Converted: ./bmp_data/moon.3.bmp
Converted: ./bmp_data/moon.2.bmp
Converted: ./bmp_data/moon.22.bmp
Converted: ./bmp_data/moon.20.bmp
Converted: ./bmp_data/moon.0.bmp
Converted: ./bmp_data/moon.1.bmp
Converted: ./bmp_data/moon.21.bmp
Converted: ./bmp_data/moon.19.bmp
Converted: ./bmp_data/moon.5.bmp
Converted: ./bmp_data/moon.4.bmp
Converted: ./bmp_data/moon.18.bmp
Converted: ./bmp_data/moon.6.bmp
Converted: ./bmp_data/moon.7.bmp
Converted: ./bmp_data/moon.16.bmp
Converted: ./bmp_data/moon.17.bmp
Converted: ./bmp_data/moon.15.bmp
Converted: ./bmp_data/moon.9.bmp
Converted: ./bmp_data/moon.8.bmp
Converted: ./bmp_data/moon.14.bmp
Converted: ./bmp_data/moon.10.bmp
Converted: ./bmp_data/moon.11.bmp
Converted: ./bmp_data/moon.13.bmp
Converted: ./bmp_data/moon.12.bmp


In [1]:
from script.photostereo import photometry
import cv2 as cv
import time
import numpy as np


IMAGES = 24
root_fold = "./bmp_data/"
obj_name = "moon."
format = ".bmp"
light_manual = False

#Load input image array
image_array = []
for id in range(0, IMAGES):
    try:
        filename = root_fold + str(obj_name) + str(id) + "_resized" + format
        im = cv.imread(root_fold + str(obj_name) + str(id) + format, cv.IMREAD_GRAYSCALE)
        image_array.append(im)
    except cv.error as err:
        print(err)

myps = photometry(IMAGES, False)

if light_manual:
    # SETTING LIGHTS MANUALLY
    #tilts = [136.571, 52.4733, -40.6776, -132.559]
    #slants = [52.6705, 53.2075, 47.3992, 48.8037]
    #slants = [37.3295, 36.7925, 42.6008, 41.1963]

    #tilts = [139.358, 50.7158, -42.5016, -132.627]
    #slants = [74.3072, 70.0977, 69.9063, 69.4498]
    #tilts = [0, 270, 180, 90]
    #slants = [45, 45, 45, 45]

    slants = [71.4281, 66.8673, 67.3586, 67.7405]
    tilts = [140.847, 47.2986, -42.1108, -132.558]

    slants = [42.9871, 49.5684, 45.9698, 43.4908]
    tilts = [-137.258, 140.542, 44.8952, -48.3291]

    myps.setlmfromts(tilts, slants)
    print(myps.settsfromlm())
else:
    # LOADING LIGHTS FROM FILE
    fs = cv.FileStorage("./bmp_data/LightMatrixOriginal.yml", cv.FILE_STORAGE_READ)
    fn = fs.getNode("Lights")
    light_mat = fn.mat()
    myps.setlightmat(light_mat)
    #print(myps.settsfromlm())

tic = time.perf_counter()
# mask = cv.imread(root_fold + "mask" + format, cv.IMREAD_GRAYSCALE)
normal_map = myps.runphotometry(image_array, mask=None)
normal_map = cv.normalize(normal_map, None, 0, 255, cv.NORM_MINMAX, cv.CV_8UC3)
albedo = myps.getalbedo()
albedo = cv.normalize(albedo, None, 0, 255, cv.NORM_MINMAX, cv.CV_8UC1)
# gauss = myps.computegaussian()
# med = myps.computemedian()

cv.imwrite('./output/normal_map_2.png',normal_map)
cv.imwrite('./output/albedo_2.png',albedo)
# cv.imwrite('./output/gauss.png',gauss)
# cv.imwrite('./output/med.png',med)

toc = time.perf_counter()
print("Process duration: " + str(toc - tic))

# TEST: 3d reconstruction
# myps.computedepthmap()
myps.computedepth2()
myps.display3dobj()
cv.imshow("normal", normal_map)
#cv.imshow("mean", med)
#cv.imshow("gauss", gauss)
cv.waitKey(0)
cv.destroyAllWindows()

Light matrix set
Running main process. Be patient...
Normal map computation end 
Process duration: 0.06992279199766926
Experimental
[[ 1. -1.  0.]
 [ 1.  0. -1.]]
[[ 0.33333334  0.33333334]
 [-0.6666666   0.3333333 ]
 [ 0.3333333  -0.6666666 ]]


: 

In [1]:
import numpy as np

# Generate the first and second columns with values ranging from -1.5708 to 1.5708
column1 = np.random.uniform(-1.5708, 1.5708, 24)
column2 = np.random.uniform(-1.5708, 1.5708, 24)

# Create the third column with all values set to 1
column3 = np.random.uniform(0, 1, 24)

# Combine the three columns into a list of tuples
data = list(zip(column1, column2, column3))

# Print the data in the desired format
for row in data:
    print("{:.6f}, {:.6f}, {:.6f},".format(row[0], row[1], row[2]))

-0.894524, -0.388804, 0.305387,
1.190211, 0.651521, 0.841057,
0.276662, 0.222518, 0.779346,
-0.613543, 0.172598, 0.244837,
1.023523, 0.320343, 0.925234,
0.690336, 0.838058, 0.500630,
0.709392, 0.565092, 0.416807,
-0.158964, -0.880932, 0.878311,
-0.234255, -0.846046, 0.166051,
1.343170, 1.145846, 0.547624,
0.773940, -0.387599, 0.314930,
-1.334484, 1.191248, 0.806813,
1.087602, -0.488965, 0.849142,
0.829564, 0.731835, 0.087550,
-0.243706, -0.827418, 0.450975,
1.015267, -0.672167, 0.545328,
0.404608, 1.050171, 0.420329,
-0.949336, -1.260537, 0.009316,
-1.215530, -1.009126, 0.421422,
1.141734, 1.337840, 0.019242,
-1.174084, 1.110816, 0.974806,
-1.401679, -1.051465, 0.146830,
1.537384, -1.254931, 0.463317,
0.553483, -0.206227, 0.888512,
